Updated dependencies

diff --git a/deps/github.com/coreos/etcd/test b/deps/github.com/coreos/etcd/test
--- a/deps/github.com/coreos/etcd/test
+++ b/deps/github.com/coreos/etcd/test
@@ -10,23 +10,30 @@
 # PKG=snap ./test
 set -e
 
+# TODO: 'client' pkg fails with gosimple from generated files
+# TODO: 'rafttest' is failing with unused
+GOSIMPLE_UNUSED_PATHS=$(go list ./... | sed -e 's/github.com\/coreos\/etcd\///g' | grep -vE 'cmd|vendor|rafttest|github.com/coreos/etcd$|client$')
+
 # Invoke ./cover for HTML output
 COVER=${COVER:-"-cover"}
 
-GO_BUILD_FLAGS=-a
+GO_BUILD_FLAGS="-a -v"
 source ./build
 
+# Set up gopath so tests use vendored dependencies
+export GOPATH=${PWD}/gopath
+rm -rf $GOPATH/src
+mkdir -p $GOPATH
+ln -s ${PWD}/cmd/vendor $GOPATH/src
+
 # Hack: gofmt ./ will recursively check the .git directory. So use *.go for gofmt.
-TESTABLE_AND_FORMATTABLE="client clientv3 discovery error etcdctl/command etcdmain etcdserver etcdserver/auth etcdserver/etcdhttp etcdserver/etcdhttp/httptypes pkg/fileutil pkg/flags pkg/idutil pkg/ioutil pkg/netutil pkg/osutil pkg/pbutil pkg/types pkg/transport pkg/wait proxy raft snap storage storage/backend store version wal"
-# TODO: add it to race testing when the issue is resolved
-# https://github.com/golang/go/issues/9946
-NO_RACE_TESTABLE="rafthttp"
-FORMATTABLE="$TESTABLE_AND_FORMATTABLE $NO_RACE_TESTABLE *.go etcdctl/ integration clientv3/integration e2e"
+PKGS=`ls pkg/*/*go  | cut -f1,2 -d/ | sort | uniq`
+TESTABLE_AND_FORMATTABLE="auth client clientv3 discovery error etcdctl/ctlv2 etcdctl/ctlv3 etcdmain etcdserver etcdserver/auth etcdserver/api/v2http etcdserver/api/v2http/httptypes etcdserver/api/v3rpc etcdserver/api/v3rpc/rpctypes $PKGS proxy/httpproxy proxy/tcpproxy raft snap mvcc mvcc/backend store version wal rafthttp"
+FORMATTABLE="$TESTABLE_AND_FORMATTABLE *.go etcdctl/ integration clientv3/integration e2e alarm"
 
 # user has not provided PKG override
 if [ -z "$PKG" ]; then
 	TEST=$TESTABLE_AND_FORMATTABLE
-	NO_RACE_TEST=$NO_RACE_TESTABLE
 	FMT=$FORMATTABLE
 
 # user has provided PKG override
@@ -43,26 +50,28 @@ fi
 # split TEST into an array and prepend REPO_PATH to each local package
 split=(${TEST// / })
 TEST=${split[@]/#/${REPO_PATH}/}
-split=(${NO_RACE_TEST// / })
-NO_RACE_TEST=${split[@]/#/${REPO_PATH}/}
+MACHINE_TYPE=$(uname -m)
+if [ $MACHINE_TYPE != "armv7l" ]; then
+	RACE="--race"
+fi
 
 function unit_tests {
 	echo "Running tests..."
-
-	MACHINE_TYPE=$(uname -m)
-	if [ $MACHINE_TYPE != "armv7l" ]; then
-		RACE="--race"
-	fi
-	go test -timeout 3m ${COVER} ${RACE} -cpu 1,2,4 $@ ${TEST}
-	go test -timeout 3m ${COVER} -cpu 1,2,4 $@ ${NO_RACE_TEST}
+	# only -run=Test so examples can run in integration tests
+	go test -timeout 3m ${COVER} ${RACE} -cpu 1,2,4 -run=Test $@ ${TEST}
 }
 
 function integration_tests {
 	echo "Running integration tests..."
-	go test -timeout 10m -v -cpu 1,2,4 $@ ${REPO_PATH}/e2e
-	go test -timeout 15m -v -cpu 1,2,4 $@ ${REPO_PATH}/integration
-	go test -timeout 10m -v -cpu 1,2,4 $@ ${REPO_PATH}/clientv3/integration
+	go test -timeout 10m -v -cpu 1,2,4 $@ ${REPO_PATH}/e2e &
+	e2epid="$!"
+	go test -timeout 15m -v -cpu 1,2,4 $@ ${REPO_PATH}/integration &
+	intpid="$!"
+	wait $e2epid
+	wait $intpid
+	go test -timeout 10m -v ${RACE} -cpu 1,2,4 $@ ${REPO_PATH}/clientv3/integration
 	go test -timeout 1m -v -cpu 1,2,4 $@ ${REPO_PATH}/contrib/raftexample
+	go test -timeout 1m -v ${RACE} -cpu 1,2,4 -run=Example $@ ${TEST}
 }
 
 function fmt_tests {
@@ -80,29 +89,62 @@ function fmt_tests {
 		exit 255
 	fi
 
-	echo "Checking govet -shadow..."
+	echo "Checking 'go tool vet -shadow'..."
 	for path in $FMT; do
+		if [ "${path##*.}" != "go" ]; then
+			path="${path}/*.go"
+		fi
 		vetRes=$(go tool vet -shadow ${path})
 		if [ -n "${vetRes}" ]; then
-			echo -e "govet checking ${path} failed:\n${vetRes}"
+			echo -e "govet -shadow checking ${path} failed:\n${vetRes}"
 			exit 255
 		fi
 	done
 
-	echo "Checking goword..."
-	# get all go files to process
-	gofiles=`find $FMT -iname '*.go' 2>/dev/null`
-	# ignore tests and protobuf files
-	gofiles=`echo ${gofiles} | sort | uniq | sed "s/ /\n/g" | egrep -v "(\\_test.go|\\.pb\\.go)"`
-	# only check for broken exported godocs
-	gowordRes=`goword -use-spell=false ${gofiles} | grep godoc-export | sort`
-	if [ ! -z "$gowordRes" ]; then
-		echo -e "goword checking failed:\n${gowordRes}"
-		exit 255
+	if which goword >/dev/null; then
+		echo "Checking goword..."
+		# get all go files to process
+		gofiles=`find $FMT -iname '*.go' 2>/dev/null`
+		# ignore tests and protobuf files
+		gofiles=`echo ${gofiles} | sort | uniq | sed "s/ /\n/g" | egrep -v "(\\_test.go|\\.pb\\.go)"`
+		# only check for broken exported godocs
+		gowordRes=`goword -use-spell=false ${gofiles} | grep godoc-export | sort`
+		if [ ! -z "$gowordRes" ]; then
+			echo -e "goword checking failed:\n${gowordRes}"
+			exit 255
+		fi
+	else
+		echo "Skipping goword..."
+	fi
+
+	if which gosimple >/dev/null; then
+		echo "Checking gosimple..."
+		for path in $GOSIMPLE_UNUSED_PATHS; do
+			simplResult=`gosimple $REPO_PATH/${path} || true`
+			if [ -n "${simplResult}" ]; then
+				echo -e "gosimple checking ${path} failed:\n${simplResult}"
+				exit 255
+			fi
+		done
+	else
+		echo "Skipping gosimple..."
+	fi
+	
+	if which unused >/dev/null; then
+		echo "Checking unused..."
+		for path in $GOSIMPLE_UNUSED_PATHS; do
+			unusedResult=`unused $REPO_PATH/${path} || true`
+			if [ -n "${unusedResult}" ]; then
+				echo -e "unused checking ${path} failed:\n${unusedResult}"
+				exit 255
+			fi
+		done
+	else
+		echo "Skipping unused..."
 	fi
 
 	echo "Checking for license header..."
-	licRes=$(for file in $(find . -type f -iname '*.go' ! -path './Godeps/*'); do
+	licRes=$(for file in $(find . -type f -iname '*.go' ! -path './cmd/*'); do
 			head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
 		done;)
 	if [ -n "${licRes}" ]; then
@@ -111,8 +153,22 @@ function fmt_tests {
 	fi
 }
 
-# fail fast on formatting tests
+function dep_tests {
+	echo "Checking package dependencies..."
+	# don't pull in etcdserver package
+	pushd clientv3 >/dev/null
+	badpkg="(etcdserver|mvcc)"
+	deps=`go list -f '{{ .Deps }}'  | sed 's/ /\n/g' | egrep "${badpkg}" | egrep -v "${badpkg}/" || echo ""`
+	popd >/dev/null
+	if [ ! -z "$deps" ]; then
+		echo -e "clientv3 has masked dependencies:\n${deps}"
+		exit 255
+	fi
+}
+
+# fail fast on static tests
 fmt_tests
+dep_tests
 
 unit_tests
 if [ -n "$INTEGRATION" ]; then
diff --git a/deps/github.com/coreos/fleet/build-aci b/deps/github.com/coreos/fleet/build-aci
--- a/deps/github.com/coreos/fleet/build-aci
+++ b/deps/github.com/coreos/fleet/build-aci
@@ -1,5 +1,4 @@
-#!/bin/bash
-set -e
+#!/bin/bash -e
 
 if [ $# -ne 1 ]; then
     echo "Usage: $0 tag" >/dev/stderr
@@ -10,13 +9,18 @@ tag=$1
 
 tgt=$(mktemp -d)
 
+# Cleanup
+trap 'rm -rf "$tgt"' INT TERM EXIT
+
+CDIR=$(cd `dirname $0` && pwd)
+
 # Build fleet inside
-docker run -v $PWD:/opt/fleet google/golang:1.4 /bin/bash -c "cd /opt/fleet && ./build"
+docker run --rm -v $CDIR:/opt/fleet -u $(id -u):$(id -g) golang:1.6 /bin/bash -c "cd /opt/fleet && ./build"
 
 # Generate manifest into target tmp dir
 cat <<DF >${tgt}/manifest
 {
-   "acVersion" : "0.5.1",
+   "acVersion" : "0.7.1",
    "acKind" : "ImageManifest",
    "name" : "coreos.com/fleetd",
    "labels" : [
@@ -81,10 +85,7 @@ cp bin/fleetd $tgt/rootfs/bin
 touch $tgt/rootfs/etc/resolv.conf
 
 # Build ACI
-actool build -overwrite $tgt fleetd-${tag}.aci
+actool build --overwrite --owner-root $tgt "fleetd-${tag}.aci"
 
 # Validate ACI
-actool validate fleetd-${tag}.aci
-
-# Cleanup
-rm -rf $tgt
+actool validate "fleetd-${tag}.aci"
